/**
 * Translation file
 */
 
 // 2010/01/14 : EAM added new dields IpStatus, MasterIpLost & MasterIpTimeouts. Reviewed by PDU
 // 2011/08/26 : GGo added profibus field 
var lang = 
{ 
  name:            "Name",
  type:            "Type",
  format:          "Format",
  value:           "Value",
  refreshPeriod:   "refresh pediod",
  list:            "list",
  variable:        "variable",
  load:            "load",
  save:            "save",
  add:             " add       ",
  del:             " del       ",
  refresh:         "refresh",
  maxVariable:     "Maximum variable count reach",
  maxList:         "Maximum list count reach",
  exists:          " already exists",
  paramNotLoaded:  "parameters NOT loaded",
  paramSaved:      "parameters saved",
  paramNotSaved:   "parameters NOT saved",
  reset:           "reset",
  status:          "Status",
  version:         "Version",
  configuration:   "Configuration",
  serialNumber:    "Serial Number",
  extModules:      "Expansion modules",
  extension:       "Expansion",
  moduleRef:       "Module reference",
  diagnostic:      "Diagnostic",
  mapping:         "Mapping",
  address:         "Address",
  identification:  "Identification",
  extensionBus:    "Extension bus",
  file:            "File",
  currentIp:       "Current IP",
  mbsStat:         "Modbus statistics",
  ethPort0:        "Ethernet_1",
  ethPort1:        "Ethernet_2",
  ethModule:       "TM4ES4",
  ethStat:         "Ethernet statistics",
  fdr:             "Fast device replacement",
  serial:          "Serial",
  ethipStat:       "Ethernet IP statistics",
  doyoureally:	   "Do you really want to",
  forbidden:       "Only alphanumeric characters are allowed",
  profibus:        "Profibus Slave",
  alertMessage401: "You are not authorized to perform this operation",
  alertMessage410: "Your session has expired. You will be redirected to the login page",
  PLC_R: {
    VendorID: "VendorID",
    ProductID: "ProductID",
    SerialNumber: "Serial Number",
    FirmVersion: "Firmware",
    BootVersion: "Boot",
    HardVersion: "Hardware",
    ChipVersion: "Coprocessor",
    Status: "Application status",
    BootProjectStatus: "Boot project status",
    LastStopCause: "Last stop cause",
    LastApplicationError: "Last application error",
    SystemFault_1: "System Fault 1",
    SystemFault_2: "System Fault 2",
    LocalIOStatus: "IO Status 1",
    TM3IOStatus: "IO Status 2",
    ClockBatterystatus: "Clock Battery Status",
	AppliSignature1: "Application signature 1" ,
	AppliSignature2: "Application signature 2" ,
	AppliSignature3: "Application signature 3" ,
	AppliSignature4: "Application signature 4" ,
    VendorName: "Vendor name",
    ProductRef: "Product reference",
    NodeName: "Node name",
    LastStopTime: "Last stop time",
    LastPowerOffDate: "Last power-off time",
    EventsCounter: "Events counter",
    TerminalPortStatus: "Prg Port : Terminal prg port status",
    SdCardStatus: "SdCard",
    UsrFreeFileHdl: "File system free handle",
    UsrFsTotalBytes: "File system total bytes",
    UsrFsFreeBytes: "File system free bytes",
    To_XBusState: "TM3 Bus status",
    To_XSyncErrCnt: "Sync error count",
    To_XAsynErrCnt: "ASync error count",
    To_XBreakCnt: "Break count",
    To_XTopoChangedCnt: "Topology change count",
    To_XBusCycleCnt: "Cycle count"
  },
  ETH_R: {
    IPAddress: "IP address",
    SubNetMask: "Subnet mask",
    Gateway: "Gateway address",
    MACAddress: "MAC address",
    DeviceName: "Device name",
    IpMode: "IP mode",
    IPAddress_If2: "IP address",
    SubNetMask_If2: "Subnet mask",
    Gateway_If2: "Gateway address",
    MACAddress_If2: "MAC address",
    DeviceName_If2: "Device name",
    IpMode_If2: "IP mode",
    FDRServerIPAddress: "FDR server",
    OpenTcpConnections: "Opened Tcp connections",
    FramesTransmittedOK: "Frames transmitted OK",
    FramedReceivedOK: "Frames received OK",
    TransmitBufferErrors: "Buffers transmitted NOK",
    ReceiveBufferErrors: "Buffers received NOK",
    FrameSendingProtocol: "Frame sending protocol",
    PortALinkStatus: "Status",
    PortASpeed: "Speed",
    PortADuplexStatus: "Duplex mode",
    PortACollisions: "Collisions",
    PortALinkStatus_If2:"Status",
    PortASpeed_If2:"Speed",
    PortADuplexStatus_If2: "Duplex mode",
    ModbusMessageTransmitted: "Messages transmitted OK",
    ModbusMessageReceived: "Messages received OK",
    ModbusErrorMessage: "Error messages",
    i_udiETHIP_IOMessagingTransmitted: "IO Messages transmitted",
    i_udiETHIP_IOMessagingRceived: "IO Messages received",
    i_udiUCMM_Request: "UCMM Request",
    i_udiUCMM_Error: "UCMM Error",
    i_udiClass3_Request: "Class3 Request",
    i_udiClass3_Error: "Class3 Error",
    i_uiAssemblyInstanceInput: "Assembly Instance Input",
    i_uiAssemblyInstanceInputSize: "Assembly Instance Input size",
    i_uiAssemblyInstanceOutput: "Assembly Instance Output",
    i_uiAssemblyInstanceOutputSize: "Assembly Instace Output size",
    i_uiETHIP_ConnectionTimeouts: "Connection timeouts",
    MasterIpTimeouts : "IpMaster timeout event counter",
    MasterIpLost : "IpMaster connection status",
    PortAIpStatus : "Ip Status"
  },
  SER_R: {
    FramesTransmittedOK: "Frames transmitted OK",
    FramesReceivedOK:"Frames received OK",
    RX_MessagesError:"RX Message error",
    SlaveExceptionCount:"Slave exception count",
	SlaveMsgCount:"Slave message count",
    SlaveNoRespCount:"Slave no response count",
    SlaveNakCount:"Slave Nak count",
    SlaveBusyCount:"Slave busy count",
	CharOverrunCount:"Character overrun count"
  },
  XMODULE: {
    ProductRefID: "ModuleID",
    //SerialNumber: "Serial number",
    //FirmVersion: "Firmware version",
    //BootVersion: "Boot version",
    State: "Status"
  },
  PB_R:{
    wPNOIdentifier: "Identification Number",
    wBusAddr: "Bus address",
    iCommState: "Module status",
    iCommError: "Communication error",
    iErrorCount: "Communication error count"
  }
}

